/* GENERATED by scripts/dc-export-data.ts — do not edit. */
#ifndef HERDER_LANG_DATA_H
#define HERDER_LANG_DATA_H

enum { POS_noun, POS_insult, POS_adj, POS_interj, POS_oath, POS_swear, POS_intensifier, POS_simile, POS_verb, POS_bodypart, POS_abstract, POS_pantheon, POS_threat, POS_adverb };
#define HERDER_POS_COUNT 14
enum { TGT_sheep=1, TGT_terrain=2, TGT_weather=4, TGT_self=8, TGT_curse=16, TGT_pantheon=32, TGT_book=64, TGT_pen=128, TGT_sky=256, TGT_day=512 };
enum { EV_idle, EV_flee, EV_caught, EV_penned, EV_absurd, EV_repeatEscape, EV_finished, EV_book, EV_epitaph, EV_rain, EV_dusk, EV_walkOfShame, EV_breather, EV_bookPassed, EV_callback, EV_roof, EV_rant, EV_fog, EV_river, EV_gaze, EV_bog, EV_nettles, EV_stub, EV_cowpat, EV_wasp, EV_bite, EV_gate, EV_molehill, EV_dawn, EV_heave, EV_curious, EV_dozy, EV_crook, EV_wind, EV_lunch, EV_boulder, EV_black, EV_miscount, EV_halfway, EV_tentogo, EV_lastone, EV_scarecrow, EV_jailbreak, EV_hat, EV_streak, EV_reread, EV_rainStops, EV_fogLifts, EV_windDrops, EV_streakBroken, EV_recaptured, EV_nemesis, EV_nemesisCaught, EV_rival, EV_rivalGone, EV_cow, EV_curseReply, EV_lunchStolen, EV_thiefCaught, EV_hens, EV_dogHelps, EV_dogUnderfoot, EV_inn, EV_rivalBolt, EV_stick, EV_levelUp, EV_signpost, EV_drink, EV_flytingReply };
#define HERDER_EVENT_COUNT 69

typedef struct {
  const char *w; unsigned char pos, band; short level;
  const char *const *reg; unsigned char reg_n;
  const char *pl; const char *forms[3]; short syl;
  const char *lang; unsigned short targets; const char *pack;
} LexEntry;

typedef struct {
  const char *id; short tier; const char *tmpl; float weight;
  short min_level; unsigned char min_band, event;
  const char *const *reg; unsigned char reg_n;
  unsigned short targets; short max_chars; const char *season;
} Rule;

typedef struct { const char *t; float weight; short min_level; unsigned char min_band; const char *const *reg; unsigned char reg_n; } NTOption;
typedef struct { const char *symbol; const NTOption *options; int n; } NonTerminal;
typedef struct { const char *id,*title,*author,*pack,*reg,*colour; float when; const char *const *excerpts; int n_excerpts; } Book;

extern const char *const HERDER_POS_NAME[HERDER_POS_COUNT];
extern const char *const HERDER_EVENT_NAME[HERDER_EVENT_COUNT];
extern const LexEntry HERDER_LEXICON[]; extern const int HERDER_LEXICON_N;
extern const Rule HERDER_RULES[]; extern const int HERDER_RULES_N;
extern const NonTerminal HERDER_NONTERMS[]; extern const int HERDER_NONTERMS_N;
extern const Book HERDER_BOOKS[]; extern const int HERDER_BOOKS_N;
#endif
